// Generated by generate.mjs; entries follow domainList and problem order.
export const missionCharacters = [
  { name: "Escrow Pilot", alt: "Cyan payment crewmate with a microchip, rupee coin and secure payment terminal", src: new URL("./fintech-escrow.svg", import.meta.url).href },
  { name: "Credit Scout", alt: "Purple credit analyst crewmate with a headset and animated financial risk gauge", src: new URL("./fintech-risk.svg", import.meta.url).href },
  { name: "Clause Sentinel", alt: "Blue legal crewmate with a judicial wig and a magnifying glass scanning a contract", src: new URL("./legal-contract.svg", import.meta.url).href },
  { name: "Proof Keeper", alt: "Amber evidence keeper with a legal cap, sealed certificate and a glowing security lock", src: new URL("./legal-evidence.svg", import.meta.url).href },
  { name: "Triage Medic", alt: "Coral emergency medic with a medical cap, stethoscope and a pulsing heart monitor", src: new URL("./healthcare-triage.svg", import.meta.url).href },
  { name: "Records Guardian", alt: "White medical records crewmate wearing a teal medical band and holding a locked health record", src: new URL("./healthcare-vault.svg", import.meta.url).href },
  { name: "Orbit Watcher", alt: "Indigo orbital crewmate with antenna headgear, a radar panel and a drifting satellite", src: new URL("./spacetech-orbit.svg", import.meta.url).href },
  { name: "Rover Ranger", alt: "Orange rover engineer with a communications headset and a little rolling exploration rover", src: new URL("./spacetech-rover.svg", import.meta.url).href },
  { name: "Crop Scout", alt: "Lime crop scientist in a straw hat scanning a leaf with a magnifying glass", src: new URL("./agritech-crop.svg", import.meta.url).href },
  { name: "Rain Maker", alt: "Yellow irrigation crewmate with a sprout cap and a watering can pouring animated droplets", src: new URL("./agritech-irrigation.svg", import.meta.url).href },
];
